package authMiddleware

import (
	"net/http"
	"strings"
	"sync"

	"github.com/kwhitestone/prism-fusion/addons/auth/service"
	"github.com/kwhitestone/prism-fusion/global"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

// 不需要认证的路径白名单
var publicPaths = []string{
	"/api/v1/addons/auth/login",
	"/api/v1/addons/auth/register",
	"/api/v1/addons/auth/refresh-token",
	"/api/v1/addons/auth/logout",
	"/api/llm-proxy",     // LLM 代理：用 x-llm-proxy-key 自鉴权（executor S2S）
	"/api/v1/addons/s2s", // Executor S2S：用 X-Executor-Token 自鉴权
	"/health",
	"/openapi",
	"/docs",
	"/scalar",
}

// publicPathsMu 保护 publicPaths 的并发追加。
var publicPathsMu sync.RWMutex

// AddPublicPath 运行时追加一个免 JWT 认证的路径前缀（供自鉴权的 S2S 插件用）。
func AddPublicPath(prefix string) {
	publicPathsMu.Lock()
	defer publicPathsMu.Unlock()
	publicPaths = append(publicPaths, prefix)
}

// JwtAuthMiddleware JWT 认证全局中间件
// 对 /api/ 路径强制认证（白名单除外），非 API 路径直接放行
func JwtAuthMiddleware() gin.HandlerFunc {
	jwtService := &service.JwtService{}
	refreshSessionService := &service.RefreshSessionService{}

	return func(c *gin.Context) {
		path := c.Request.URL.Path
		if c.Request.Method != http.MethodOptions && !enforceAuthRateLimit(c, path) {
			return
		}

		// 非 API 路径直接放行（静态文件、前端页面等）
		if !strings.HasPrefix(path, "/api/") {
			c.Next()
			return
		}

		// 白名单路径放行
		publicPathsMu.RLock()
		paths := publicPaths
		publicPathsMu.RUnlock()
		for _, p := range paths {
			if path == p || strings.HasPrefix(path, p) {
				c.Next()
				return
			}
		}

		// 提取 Token
		tokenStr := c.GetHeader("Authorization")
		if tokenStr == "" {
			c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{
				"code":    401,
				"message": "未提供认证令牌",
			})
			return
		}

		// 去除 Bearer 前缀
		if strings.HasPrefix(tokenStr, "Bearer ") {
			tokenStr = tokenStr[7:]
		}

		// 解析验证 Token
		claims, err := jwtService.ParseAccessToken(tokenStr)
		if err != nil {
			global.PRISM_LOG.Debug("JWT 验证失败",
				zap.String("path", path),
				zap.Error(err),
			)
			c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{
				"code":    401,
				"message": "认证令牌无效或已过期",
			})
			return
		}
		// Human sessions must be revocable. Role 0 is reserved for internal
		// service JWTs generated by core; historical user JWTs without sid are
		// intentionally forced through a one-time re-login after this upgrade.
		if claims.SessionID == "" && claims.RoleID != 0 {
			c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{
				"code":    401,
				"message": "旧版会话已失效，请重新登录",
			})
			return
		}
		if claims.SessionID != "" {
			active, sessionErr := refreshSessionService.IsFamilyActive(
				claims.UserID,
				claims.SessionID,
			)
			if sessionErr != nil {
				global.PRISM_LOG.Error("访问会话验证失败",
					zap.String("path", path),
					zap.Error(sessionErr),
				)
				c.AbortWithStatusJSON(http.StatusServiceUnavailable, gin.H{
					"code":    503,
					"message": "认证服务暂时不可用",
				})
				return
			}
			if !active {
				c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{
					"code":    401,
					"message": "会话已失效，请重新登录",
				})
				return
			}
		}

		// 将用户信息写入 Context，供后续处理使用
		c.Set("user_id", claims.UserID)
		c.Set("username", claims.Username)
		c.Set("role_id", claims.RoleID)
		c.Set("session_id", claims.SessionID)
		if claims.ExpiresAt != nil {
			c.Set("token_expires_at", claims.ExpiresAt.Time)
		}

		c.Next()
	}
}
